server {
    listen 80;

    # 1. Tudo que for visual (o site em si) vai para o Frontend
    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Quando o site pedir a rota de Chat, vai para o Backend
    location /chat {
        proxy_pass http://backend:8000/chat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Quando o site pedir a rota de Analisar, vai para o Backend
    location /analisar {
        proxy_pass http://backend:8000/analisar;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Libera a documentação automática do FastAPI (para você testar)
    location /docs {
        proxy_pass http://backend:8000/docs;
    }
    location /openapi.json {
        proxy_pass http://backend:8000/openapi.json;
    }
}